import { clsx, type ClassValue } from "clsx";
import dayjs from "dayjs";
import "dayjs/locale/es-mx";
import relativeTime from "dayjs/plugin/relativeTime";
import { twMerge } from "tailwind-merge";

// generated by shadcn
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// created by chatgpt
export function isBase64Image(imageData: string) {
  const base64Regex = /^data:image\/(png|jpe?g|gif|webp);base64,/;
  return base64Regex.test(imageData);
}

export function formatDateString(dateString: string, mode: string) {
  if (mode === "short") {
    dayjs.extend(relativeTime);
    dayjs.locale("es-mx");

    return dayjs(dateString).fromNow();
  } else {
    const date = new Date(dateString);
    
    const formattedDate = date.toLocaleDateString();

    const time = date.toLocaleTimeString([], {
      hour: "numeric",
      minute: "2-digit",
    });

    return `${time} - ${formattedDate}`;
  }
}
